# Generated by Django 4.0.2 on 2022-07-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategoy',
            new_name='ProductCategory',
        ),
    ]
