# Generated by Django 4.0.2 on 2022-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_productcategoy_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
